//tealium universal tag - utag.1756 ut4.0.201705050500, Copyright 2017 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<35){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={"view":1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.map={"dom.url":"ft_referrer","dom.referrer":"ns"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:1756");utag.DB(b);var c,d,e,f;u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"//servedby.flashtalking.com","tag_type":"iframe","account":"10230","spot1":"75043","spot2":"7784","spotName":"","ftRandom":Math.random()*1000000,"order_id":"","order_subtotal":"","order_currency":"","product_quantity":[]};utag.DB("send:1756:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(u.data.hasOwnProperty(e[f])){u.data[e[f]]=encodeURIComponent(b[d]);}else if(e[f]=='ns'){c.push(e[f]+u.data.kvp_delim+b[d]);}else{c.push(e[f]+u.data.kvp_delim+encodeURIComponent(b[d]));}}}}
utag.DB("send:1756:MAPPINGS");utag.DB(u.data);u.data.order_id=u.data.order_id||b._corder||"";u.data.order_subtotal=u.data.order_subtotal||b._csubtotal||"";u.data.order_currency=u.data.order_currency||b._ccurrency||"";if(u.data.product_quantity.length===0&&b._cquan!==undefined){u.data.product_quantity=b._cquan.slice(0);}
if(!u.data.account){utag.DB(u.id+": Tag not fired: Required attribute not populated");return;}
if(!u.data.ftXNumItems&&u.data.product_quantity){u.data.ftXNumItems=0;for(var i=0;i<u.data.product_quantity.length;i++){u.data.ftXNumItems+=parseInt(u.data.product_quantity[i]);}}
if(u.data.spotName){c.push(["spotName",u.data.spotName].join(u.data.kvp_delim));}
if(u.data.order_id){c.push(["ftXRef",u.data.order_id].join(u.data.kvp_delim));if(u.data.order_subtotal){c.push(["ftXValue",u.data.order_subtotal].join(u.data.kvp_delim));}
if(u.data.ftXNumItems){c.push(["ftXNumItems",u.data.ftXNumItems].join(u.data.kvp_delim));}
if(u.data.order_currency){c.push(["ftXCurrency",u.data.order_currency].join(u.data.kvp_delim));}}
c.push(["cachebuster",u.data.ftRandom].join(u.data.kvp_delim));if(u.data.tag_type=="pixel"){var src=u.data.base_url+"/spot/"+u.data.account+";"+u.data.spot1+";"+u.data.spot2+"/?";u.loader({"type":"img","src":src+c.join(u.data.qsp_delim)});}else{if(!u.initialized){var src=u.data.base_url+"/container/"+u.data.account+";"+u.data.spot1+";"+u.data.spot2+";iframe/?";u.loader({"type":"iframe","src":src+c.join(u.data.qsp_delim),"cb":function(){u.initialized=true;},"loc":"body","id":"utag_1756"});}}
utag.DB("send:1756:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("1756","samsung.main"));}catch(error){utag.DB(error);}
